### ISSUE TITLE
Readme file

### ISSUE THREAD

**Issue by tedstriker** [HendrikRoth/node-red-contrib-tankerkoenig#1]
Hi there,

is there a chance that a readme file explaining how to use the node will be created?

cheers
Ted

**Comment by StephanStS** [comment]
@tedstriker: I have generated a node description in german language there: <https://github.com/StephanStS/node-red-contrib-tankerkoenig>.  
Is this what you needed?

**Comment by HendrikRoth** [comment]
Nice Work! Please make an pull request :-).

**Comment by StephanStS** [comment]
... in work. Last typos cleared.

**Comment by StephanStS** [comment]
@HendrikRoth: See also my email to you from 07.10.20, 10:04.

**Comment by HendrikRoth** [comment]
PR #2
